CREATE TABLE CATEGORY(
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(30),
    DESCRIPTION VARCHAR2(50)
);

INSERT INTO CATEGORY VALUES(1,'FRUITS','Fresh fruits');

INSERT INTO CATEGORY VALUES(2,'VEGETABLES','Fresh vegetables');

INSERT INTO CATEGORY VALUES(3,'DAIRY','Milk and dairy products');

INSERT INTO CATEGORY VALUES(4,'SNACKS','Snacks and biscuits');

INSERT INTO CATEGORY VALUES(5,'BEVERAGES','Juices and soft drinks');

SELECT * FROM CATEGORY;