 CREATE TABLE INVENTORY(
    INVENTORY_ID NUMBER PRIMARY KEY,
    SELLER_ID NUMBER,
    PRODUCT_ID NUMBER,
    STOCK_QUANTITY NUMBER,
    STOCK_STATUS VARCHAR2(20),
    FOREIGN KEY(SELLER_ID) REFERENCES SELLER(SELLER_ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

INSERT INTO INVENTORY VALUES(301,201,101,50,'AVAILABLE');

INSERT INTO INVENTORY VALUES(302,202,102,80,'AVAILABLE');

INSERT INTO INVENTORY VALUES(303,203,103,70,'AVAILABLE');

INSERT INTO INVENTORY VALUES(304,204,104,90,'AVAILABLE');

INSERT INTO INVENTORY VALUES(305,205,105,0,'UNAVAILABLE');

SELECT * FROM INVENTORY;

SELECT S.SELLER_NAME,
       P.PRODUCT_NAME,
       I.STOCK_QUANTITY,
       I.STOCK_STATUS
FROM SELLER S
JOIN INVENTORY I
ON S.SELLER_ID = I.SELLER_ID
JOIN PRODUCT P
ON I.PRODUCT_ID = P.PRODUCT_ID;

SELECT P.PRODUCT_NAME,
       I.STOCK_QUANTITY,
       I.STOCK_STATUS
FROM PRODUCT P
JOIN INVENTORY I
ON P.PRODUCT_ID = I.PRODUCT_ID
WHERE I.STOCK_STATUS = 'AVAILABLE';

SELECT P.PRODUCT_NAME,
       I.STOCK_QUANTITY,
       I.STOCK_STATUS
FROM PRODUCT P
JOIN INVENTORY I
ON P.PRODUCT_ID = I.PRODUCT_ID
WHERE I.STOCK_STATUS = 'UNAVAILABLE';