CREATE TABLE ORDERS(
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    ORDER_STATUS VARCHAR2(20),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

INSERT INTO ORDERS VALUES(401,101,TO_DATE('20-09-2026','DD-MM-YYYY'),180,'DELIVERED');

INSERT INTO ORDERS VALUES(402,102,TO_DATE('21-09-2026','DD-MM-YYYY'),120,'PROCESSING');

INSERT INTO ORDERS VALUES(403,103,TO_DATE('22-09-2026','DD-MM-YYYY'),140,'SHIPPED');

INSERT INTO ORDERS VALUES(404,104,TO_DATE('23-09-2026','DD-MM-YYYY'),105,'DELIVERED');

INSERT INTO ORDERS VALUES(405,105,TO_DATE('24-09-2026','DD-MM-YYYY'),60,'PROCESSING');

SELECT * FROM ORDERS;

UPDATE ORDERS
SET ORDER_STATUS = 'SHIPPED'
WHERE ORDER_ID = 402;

UPDATE ORDERS
SET TOTAL_AMOUNT = 120
WHERE ORDER_ID = 405;

SELECT C.CUSTOMER_NAME,
       O.ORDER_ID,
       O.ORDER_DATE,
       O.TOTAL_AMOUNT,
       O.ORDER_STATUS
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID;