CREATE TABLE ORDER_DETAILS(
    ORDER_DETAIL_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    PRICE NUMBER(10,2),
    TOTAL_PRICE NUMBER(10,2),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

INSERT INTO ORDER_DETAILS VALUES(501,401,101,1,130,130);

INSERT INTO ORDER_DETAILS VALUES(502,401,102,1,60,60);

INSERT INTO ORDER_DETAILS VALUES(503,402,102,2,60,120);

INSERT INTO ORDER_DETAILS VALUES(504,403,103,2,40,80);

INSERT INTO ORDER_DETAILS VALUES(505,403,104,2,30,60);

INSERT INTO ORDER_DETAILS VALUES(506,404,104,3,35,105);

INSERT INTO ORDER_DETAILS VALUES(507,405,102,1,60,60);

SELECT * FROM ORDER_DETAILS;

SELECT C.CUSTOMER_NAME,
       O.ORDER_ID,
       O.ORDER_DATE,
       P.PRODUCT_NAME,
       OD.QUANTITY,
       OD.PRICE,
       OD.TOTAL_PRICE,
       O.ORDER_STATUS
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_DETAILS OD
ON O.ORDER_ID = OD.ORDER_ID
JOIN PRODUCT P
ON OD.PRODUCT_ID = P.PRODUCT_ID
ORDER BY C.CUSTOMER_NAME, O.ORDER_DATE;

SELECT C.CUSTOMER_NAME,
       COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMER C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME;