CREATE TABLE PAYMENT(
    PAYMENT_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    PAYMENT_DATE DATE,
    PAYMENT_MODE VARCHAR2(30),
    PAYMENT_AMOUNT NUMBER(10,2),
    PAYMENT_STATUS VARCHAR2(20),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
INSERT INTO PAYMENT
VALUES(601,401,TO_DATE('20-09-2026','DD-MM-YYYY'),'UPI',180,'SUCCESS');

INSERT INTO PAYMENT
VALUES(602,402,TO_DATE('21-09-2026','DD-MM-YYYY'),'CREDIT CARD',120,'SUCCESS');

INSERT INTO PAYMENT
VALUES(603,403,TO_DATE('22-09-2026','DD-MM-YYYY'),'DEBIT CARD',140,'FAILED');

INSERT INTO PAYMENT
VALUES(604,404,TO_DATE('23-09-2026','DD-MM-YYYY'),'CASH ON DELIVERY',105,'PENDING');

INSERT INTO PAYMENT
VALUES(605,405,TO_DATE('24-09-2026','DD-MM-YYYY'),'UPI',120,'SUCCESS');

SELECT * FROM PAYMENT;

SELECT PAYMENT_ID,
       ORDER_ID,
       PAYMENT_MODE,
       PAYMENT_AMOUNT,
       PAYMENT_STATUS
FROM PAYMENT
WHERE PAYMENT_STATUS = 'SUCCESS';

SELECT PAYMENT_ID,
       ORDER_ID,
       PAYMENT_MODE,
       PAYMENT_AMOUNT,
       PAYMENT_STATUS
FROM PAYMENT
WHERE PAYMENT_STATUS IN ('FAILED','PENDING');

SELECT PAYMENT_MODE,
       COUNT(PAYMENT_ID) AS TOTAL_TRANSACTIONS
FROM PAYMENT
GROUP BY PAYMENT_MODE;

SELECT P.PAYMENT_ID,
       O.ORDER_ID,
       O.ORDER_DATE,
       P.PAYMENT_MODE,
       P.PAYMENT_AMOUNT,
       P.PAYMENT_STATUS
FROM ORDERS O
JOIN PAYMENT P
ON O.ORDER_ID = P.ORDER_ID
ORDER BY O.ORDER_DATE;

SELECT C.CUSTOMER_NAME,
       O.ORDER_ID,
       P.PAYMENT_MODE,
       P.PAYMENT_AMOUNT,
       P.PAYMENT_STATUS
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN PAYMENT P
ON O.ORDER_ID = P.ORDER_ID
ORDER BY C.CUSTOMER_NAME;