CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30),
    PRICE NUMBER(10,2),
    STOCK NUMBER,
    CATEGORY_ID NUMBER,
    DESCRIPTION VARCHAR2(50),
    FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

INSERT INTO PRODUCT VALUES(101,'APPLE',120,50,1,'Fresh red apples');

INSERT INTO PRODUCT VALUES(102,'BANANA',60,80,1,'Fresh bananas');

INSERT INTO PRODUCT VALUES(103,'TOMATO',40,70,2,'Fresh tomatoes');

INSERT INTO PRODUCT VALUES(104,'MILK',35,100,3,'Fresh milk');

INSERT INTO PRODUCT VALUES(105,'BISCUIT',30,60,4,'Cream biscuits');

SELECT * FROM PRODUCT;


UPDATE PRODUCT
SET PRICE = 130
WHERE PRODUCT_ID = 101;

UPDATE PRODUCT
SET STOCK = 90
WHERE PRODUCT_ID = 104;

DELETE FROM PRODUCT
WHERE PRODUCT_ID = 105;

SELECT C.CATEGORY_NAME, P.PRODUCT_NAME, P.PRICE, P.STOCK
FROM CATEGORY C
JOIN PRODUCT P
ON C.CATEGORY_ID = P.CATEGORY_ID;

SELECT P.PRODUCT_NAME, P.PRICE, P.STOCK
FROM PRODUCT P
JOIN CATEGORY C
ON P.CATEGORY_ID = C.CATEGORY_ID
WHERE C.CATEGORY_NAME = 'FRUITS';

SELECT C.CATEGORY_NAME, COUNT(P.PRODUCT_ID) AS TOTAL_PRODUCTS
FROM CATEGORY C
LEFT JOIN PRODUCT P
ON C.CATEGORY_ID = P.CATEGORY_ID
GROUP BY C.CATEGORY_NAME;