CREATE TABLE RATING(
    RATING_ID NUMBER PRIMARY KEY,
    REVIEW_ID NUMBER,
    RATING_VALUE NUMBER(1),
    FOREIGN KEY(REVIEW_ID) REFERENCES REVIEW(REVIEW_ID)
);

INSERT INTO RATING
VALUES(801,701,5);

INSERT INTO RATING
VALUES(802,702,4);

INSERT INTO RATING
VALUES(803,703,3);

INSERT INTO RATING
VALUES(804,704,5);

INSERT INTO RATING
VALUES(805,705,4);

SELECT * FROM RATING;

SELECT P.PRODUCT_NAME,
       AVG(RT.RATING_VALUE) AS AVERAGE_RATING
FROM PRODUCT P
JOIN REVIEW R
ON P.PRODUCT_ID = R.PRODUCT_ID
JOIN RATING RT
ON R.REVIEW_ID = RT.REVIEW_ID
GROUP BY P.PRODUCT_NAME
ORDER BY P.PRODUCT_NAME;

SELECT P.PRODUCT_NAME,
       AVG(RT.RATING_VALUE) AS AVERAGE_RATING
FROM PRODUCT P
JOIN REVIEW R
ON P.PRODUCT_ID = R.PRODUCT_ID
JOIN RATING RT
ON R.REVIEW_ID = RT.REVIEW_ID
GROUP BY P.PRODUCT_NAME
HAVING AVG(RT.RATING_VALUE) >= 4
ORDER BY AVERAGE_RATING DESC;

SELECT RATING_VALUE,
       COUNT(*) AS TOTAL_REVIEWS
FROM RATING
GROUP BY RATING_VALUE
ORDER BY RATING_VALUE DESC;