CREATE TABLE REVIEW(
    REVIEW_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    REVIEW_TEXT VARCHAR2(100),
    REVIEW_DATE DATE,
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

INSERT INTO REVIEW
VALUES(701,101,101,'Fresh and good quality apple',
TO_DATE('25-09-2026','DD-MM-YYYY'));

INSERT INTO REVIEW
VALUES(702,102,102,'Bananas were fresh',
TO_DATE('26-09-2026','DD-MM-YYYY'));

INSERT INTO REVIEW
VALUES(703,103,103,'Tomatoes were good',
TO_DATE('27-09-2026','DD-MM-YYYY'));

INSERT INTO REVIEW
VALUES(704,104,104,'Milk was fresh',
TO_DATE('28-09-2026','DD-MM-YYYY'));

INSERT INTO REVIEW
VALUES(705,105,105,'Biscuits were tasty',
TO_DATE('29-09-2026','DD-MM-YYYY'));

SELECT * FROM REVIEW;

SELECT C.CUSTOMER_NAME,
       P.PRODUCT_NAME,
       R.REVIEW_TEXT,
       RT.RATING_VALUE,
       R.REVIEW_DATE
FROM REVIEW R
JOIN CUSTOMER C
ON R.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCT P
ON R.PRODUCT_ID = P.PRODUCT_ID
JOIN RATING RT
ON R.REVIEW_ID = RT.REVIEW_ID
ORDER BY R.REVIEW_DATE;